name: nvchecker

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nvchecker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/liangyongxiang/gentoo-testing:master

    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: gentoo
      run: |
        for i in {1..100}; do
          (
            set -e
            # eselect
            echo "::group::eselect repository add and sync"
            eselect repository enable dlang
            emerge --sync dlang
            repo_name=$(cat profiles/repo_name)
            eselect repository add "$repo_name" git "file://${PWD}"
            emerge --sync "$repo_name"
            egencache --jobs=$(nproc) --update --repo "$repo_name" &> /dev/null
            eix-update
            echo "::endgroup::"
            # eix
            echo "::group::eix search packages"
            pkgs=$(ACCEPT_LICENSE="*" ACCEPT_KEYWORDS="~amd64 ~arm64 ~loong ~riscv" EIX_LIMIT=0 NAMEVERSION="<category>/<name>-<version>\n" eix --pure-packages --in-overlay "$repo_name" --format '<bestversion:NAMEVERSION>')
            pkgs=$(qatom -F "\"%{CATEGORY}/%{PN}\": \"%{PV}\"," $pkgs) # remove revision
            echo "$pkgs"
            pkgs="{ ${pkgs::-1} }"
            echo "$pkgs" > .github/workflows/old_ver.json
            # sed -r -i 's/_p[^"]*//' .github/workflows/old_ver.json
            cat .github/workflows/old_ver.json
            echo "::endgroup::"
          ) && break
          echo "Attempt $i failed! Retrying in 5 seconds..."
          sleep 5
        done
        if [ $i -eq 100 ]; then
          echo "All 100 attempts failed."
          exit 1
        fi

    - name: nvchecker
      id: nvchecker
      run: |
        echo "::group::nvchecker and nvcmp"
        cd .github/workflows/
        echo -e "[keys]\ngithub = \"${{ secrets.GITHUB_TOKEN }}\"" > keyfile.toml
        nvchecker --file overlay.toml --keyfile keyfile.toml

        cat new_ver.json
        echo "nvcmp=$(nvcmp --file overlay.toml --json --newer)" >> $GITHUB_OUTPUT

        echo "::endgroup::"

    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version: latest

    - name: install github-script depends
      run: |
        npm install toml

    - name: update issues
      uses: actions/github-script@v8
      timeout-minutes: 1
      env:
        pkgs: ${{steps.nvchecker.outputs.nvcmp}}
      with:
        github-token: ${{ secrets.GENTOO_NVCHECKER_PAT }} # https://github.com/microcai/gentoo-zh/pull/3130
        script: |
          const script = require('./.github/workflows/issues-bumper.js');
          (async function () {
            await script({github, context, core});
          })();
