[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

["app-editors/cursor"]
source = "regex"
url = "https://www.cursor.com/api/download?platform=linux-x64&releaseTrack=latest"
regex = '"version":"([\d.]+)"'

["net-analyzer/pwru-bin"]
source = "github"
github = "cilium/pwru"
use_latest_release = true
prefix = "v"

["net-misc/onedrive"]
source = "github"
github = "abraunegg/onedrive"
use_latest_release = true
prefix = "v"

["net-proxy/dae"]
source = "github"
github = "daeuniverse/dae"
use_latest_release = true
prefix = "v"

["net-vpn/cloudflared-bin"]
source = "github"
github = "cloudflare/cloudflared"
use_latest_release = true

["net-im/wechat"]
source = "regex"
url = "https://github.com/peeweep/wechat-linux-watcher/raw/refs/heads/master/wechat-linux-version.txt"
regex = '(.*)'

["app-text/goldendict-ng"]
source = "github"
github = "xiaoyifang/goldendict-ng"
use_latest_release = true
from_pattern = "v(.*)-.*"
to_pattern = "\\1"

["dev-util/osc"]
source = "github"
github = "openSUSE/osc"
use_latest_tag = true

["dev-util/android-tools-bin"]
source = "github"
github = "nmeum/android-tools"
use_latest_tag = true



["dev-go/staticcheck"]
source = "github"
github = "dominikh/go-tools"
use_latest_tag = true

["dev-go/gotests"]
source = "github"
github = "cweill/gotests"
use_latest_tag = true
prefix = "v"

["app-misc/opencode-bin"]
source = "github"
github = "sst/opencode"
use_latest_tag = true
prefix = "v"

["net-libs/bun-bin"]
source = "github"
github = "oven-sh/bun"
use_latest_tag = true
prefix = "bun-v"
