[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"


["app-editors/neovim-bin"]
source = "github"
github = "neovim/neovim"
use_latest_release = true
prefix = "v"

["net-analyzer/pwru-bin"]
source = "github"
github = "cilium/pwru"
use_latest_release = true
prefix = "v"

["net-misc/onedrive"]
source = "github"
github = "abraunegg/onedrive"
use_latest_release = true
prefix = "v"

["net-proxy/dae"]
source = "github"
github = "daeuniverse/dae"
use_latest_release = true
prefix = "v"

["net-vpn/cloudflared-bin"]
source = "github"
github = "cloudflare/cloudflared"
use_latest_release = true

["net-im/wechat"]
source = "regex"
url = "https://github.com/peeweep/wechat-linux-watcher/raw/refs/heads/master/wechat-linux-version.txt"
regex = '(.*)'


["dev-util/osc"]
source = "github"
github = "openSUSE/osc"
use_latest_tag = true

["dev-util/android-tools-bin"]
source = "github"
github = "nmeum/android-tools"
use_latest_tag = true

["dev-go/staticcheck"]
source = "github"
github = "dominikh/go-tools"
use_latest_tag = true

["dev-go/gotests"]
source = "github"
github = "cweill/gotests"
use_latest_tag = true
prefix = "v"

["app-misc/crush"]
source = "github"
github = "charmbracelet/crush"
use_latest_tag = true
prefix = "v"

["app-misc/cursor-agent"]
source = "regex"
url = "https://cursor.com/install"
regex = 'https:\/\/downloads\.cursor\.com\/lab\/(\d{4}\.\d{2}\.\d{2})-[^\/]+\/'

["app-misc/claude-code"]
source = "regex"
url = "https://registry.npmjs.org/@anthropic-ai/claude-code"
regex = '"latest":"([\d.]+)"'

["app-misc/gemini-cli"]
source = "regex"
url = "https://registry.npmjs.org/@google/gemini-cli"
regex = '"latest":"([\d.]+)"'

["app-misc/qwen-code"]
source = "github"
github = "QwenLM/qwen-code"
use_latest_tag = true
prefix = "v"


